pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('deploy to stage') {
            steps {
                build job: 'deploy-to-tomcat'
            }
        }
        stage('deploy to prod') {
            steps {
                build job: 'deploy-to-prod'
            }
        }
    }
}