pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            label 'Linux'
            args  '-v /tmp:/tmp'
        }
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('deploy to stage') {
            steps {
                echo "building our job in our local staging environment"
                build job: 'deploy-to-tomcat'
            }
        }
        stage('deploy to prod') {
            steps {
                echo "deploying our tomcat to tori blacks big ass"
                build job: 'deploy-to-prod'
            }
        }
    }
}